version: "3.7"
services:
    
    db:
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
        volumes: 
            - ./db-init/:/docker-entrypoint-initdb.d/
        ports: 
            - 3306:3306
    db-ui: 
        image: adminer
        ports: 
            - 8000:8080
    app:
        build: ./app
        depends_on: 
            - db
        ports: 
            - 5000:5000
        restart: always